import { addAlert, addAnomaly } from "../core/vehicleState.js";

const SCENARIO_NAME = "DENIAL_OF_SERVICE";

export const createDenialOfServiceScenario = ({
  canBus,
  clock,
  vehicleState,
  logger,
  config = {},
}) => {
  const attackStartMs = config.attackStartMs ?? 5_000;
  const attackDurationMs = config.attackDurationMs ?? 2_000;
  const messagesPerTick = Math.min(
    Math.max(Number(config.messagesPerTick ?? 5), 1),
    25,
  );
  let activated = false;
  let completed = false;

  const tick = () => {
    if (!activated && clock.timeMs >= attackStartMs) {
      activated = true;
      vehicleState.ecus.ADAS_ECU.directlyTargeted = true;
      vehicleState.network.healthScore = Math.min(vehicleState.network.healthScore, 55);

      addAnomaly(vehicleState, {
        source: "SCENARIO_ENGINE",
        type: "VIRTUAL_CAN_BUS_CONGESTION",
        severity: "HIGH",
        message: "A controlled virtual message flood is causing CAN-bus congestion.",
      });

      addAlert(vehicleState, {
        source: "SCENARIO_ENGINE",
        level: "HIGH",
        message: "Virtual CAN-bus health is degraded by a denial-of-service scenario.",
      });

      logger.log({
        timeMs: clock.timeMs,
        eventType: "SCENARIO_ACTIVATED",
        sourceEcu: "SCENARIO_ENGINE",
        targetEcu: "ADAS_ECU",
        message: "Denial-of-service scenario activated in the isolated digital twin.",
        severity: "HIGH",
        isAnomalous: true,
        data: {
          scenario: SCENARIO_NAME,
          attackDurationMs,
          messagesPerTick,
        },
      });
    }

    if (
      !activated ||
      completed ||
      clock.timeMs >= attackStartMs + attackDurationMs
    ) {
      if (activated && !completed && clock.timeMs >= attackStartMs + attackDurationMs) {
        completed = true;
        logger.log({
          timeMs: clock.timeMs,
          eventType: "SCENARIO_COMPLETED",
          sourceEcu: "SCENARIO_ENGINE",
          targetEcu: "ADAS_ECU",
          message: "Virtual denial-of-service message flood ended.",
          severity: "HIGH",
          isAnomalous: true,
          data: { scenario: SCENARIO_NAME },
        });
      }
      return;
    }

    for (let index = 0; index < messagesPerTick; index += 1) {
      canBus.transmit({
        sourceEcu: "VIRTUAL_FLOOD_SOURCE",
        targetEcu: "ADAS_ECU",
        messageType: "DIAGNOSTIC_STATUS",
        priority: "LOW",
        isAnomalous: true,
        anomalyReason:
          "Controlled excess virtual traffic generated by the denial-of-service scenario.",
        delivery: "DELAYED",
        delayedByMs: clock.tickIntervalMs,
        data: {
          scenario: SCENARIO_NAME,
          burstIndex: index + 1,
        },
      });
    }
  };

  const reset = () => {
    activated = false;
    completed = false;
  };

  return {
    name: SCENARIO_NAME,
    tick,
    reset,
  };
};